name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:18.10-alpine3.15
    steps:
      - name: Log node node-version
        run: |
         node -v 
         cat /etc/os-release