name: Matrix
on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Log a node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log a node node-version
        run: node -v


  node-version2:
    runs-on: ubuntu-latest
    steps:
      - name: Log a node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 7
      - name: Log a node node-version
        run: node -v
        