name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log a node node-version
        run: node-v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log a node node-version
        run: node-v
        